# FFmpeg Settings
ffmpeg_path: null
ffprobe_path: null

# Video Encoding Settings
video_codec: libx265
video_preset: veryslow
video_crf: 13
max_threads: 16
gpu_device: 0
copy_audio: true
copy_subtitles: true

# Language Settings
preferred_languages:
  - eng
  - jpn
  - kor
  - cmn

# HDR Settings
hdr_settings:
  preserve_hdr: true
  force_10bit: true
  preferred_format: auto  # auto, hdr10, hlg, dv
  fallback_format: hdr10  # Format to use if source format can't be preserved
  dolby_vision_enabled: true
  dolby_vision_profile: auto  # auto, 5, 8.1, 8.2, 8.4